services:
  # Caddy - Reverse Proxy avec HTTPS automatique
  caddy:
    image: caddy:2-alpine
    container_name: selfstart-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /Docker/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - BASE_DOMAIN=mserv.ovh
    networks:
      - caddy_net
    depends_on:
      - backend-api
      - frontend-loader

  # Backend API - FastAPI pour la gestion Docker
  backend-api:
    build: ./backend-api
    container_name: selfstart-backend
    restart: unless-stopped
    ports:
      - "7778:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - STARTUP_TIMEOUT=${STARTUP_TIMEOUT:-120}
      - PYTHONUNBUFFERED=1
    networks:
      - caddy_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Loader - Interface React de chargement
  frontend-loader:
    build: ./frontend-loader
    container_name: selfstart-frontend
    restart: unless-stopped
    ports:
      - "7777:3000"
    environment:
      - VITE_API_URL=http://backend-api:8000
      - VITE_POLLING_INTERVAL=${POLLING_INTERVAL:-2000}
    networks:
      - caddy_net
    depends_on:
      - backend-api

# Volumes pour la persistance des données
volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local

# Réseau pour la communication entre services
networks:
  caddy_net:
    external: true

